export default {
  GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  PRODUCT_ERROR: 'PRODUCT_ERROR'
};
