export default {
  GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  PRODUCT_ERROR: 'PRODUCT_ERROR',
  ADD_TO_CART: 'ADD_TO_CART',
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  SIGN_UP: 'SIGN_UP',
  GET_PROFILE: 'GET_PROFILE',
  DELETE_FROM_CART: 'DELETE_FROM_CART'

};
